[package]
name = "rustto-backup-mysql"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rustto-common = { path = "../common" }
rustto-core = { path = "../core" }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1"
tokio = { version = "1", features = ["process", "rt"] }
