[package]
name = "rustto-backup-file"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rustto-common = { path = "../common" }
rustto-core = { path = "../core" }
async-trait = "0.1"
serde_json = "1"
tar = "0.4"
flate2 = "1"
tokio = { version = "1", features = ["rt"] }
